services:
  # Serviço da sua aplicação FastAPI
  api:
    # Constrói a imagem a partir do Dockerfile na pasta atual
    build: .
    container_name: api
    ports:
      # Expõe a porta 8000 do contêiner para a porta 8000 do seu computador
      - "8000:8000"
    volumes:
      # Monta o código-fonte local dentro do contêiner
      # Isso permite que o uvicorn com --reload funcione corretamente
      - .:/app
